### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by thecrypt0hunter** [RedstonePlatform/Redstone#18]
Receiving this error after I stopped mining / changed the mining address and restarted redstoned

fail: Stratis.Bitcoin.Builder.FullNodeFeatureExecutor[0]
      An error occurred starting the application: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) (Value cannot be null.
      Parameter name: block) ---> System.NullReferenceException: Object reference not set to an instance of an object.
         at Stratis.Bitcoin.Features.Consensus.StakeChainStore.LoadAsync() in /home/thecryptohunter/projects/Redstone/src/Stratis.Bitcoin.Features.Consensus/StakeChainStore.cs:line 60
         at Stratis.Bitcoin.Features.Consensus.Rules.PosConsensusRuleEngine.Initialize() in /home/thecryptohunter/projects/Redstone/src/Stratis.Bitcoin.Features.Consensus/Rules/PosConsensusRuleEngine.cs:line 52
         at Stratis.Bitcoin.Base.BaseFeature.Initialize() in /home/thecryptohunter/projects/Redstone/src/Stratis.Bitcoin/Base/BaseFeature.cs:line 206
         at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Initialize>b__3_1(IFullNodeFeature service) in /home/thecryptohunter/projects/Redstone/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 57
         at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in /home/thecryptohunter/projects/Redstone/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 102
         --- End of inner exception stack trace ---
         at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in /home/thecryptohunter/projects/Redstone/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 120
         at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Initialize() in /home/thecryptohunter/projects/Redstone/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 57
      ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
         at Stratis.Bitcoin.Features.Consensus.StakeChainStore.LoadAsync() in /home/thecryptohunter/projects/Redstone/src/Stratis.Bitcoin.Features.Consensus/StakeChainStore.cs:line 60
         at Stratis.Bitcoin.Features.Consensus.Rules.PosConsensusRuleEngine.Initialize() in /home/thecryptohunter/projects/Redstone/src/Stratis.Bitcoin.Features.Consensus/Rules/PosConsensusRuleEngine.cs:line 52
         at Stratis.Bitcoin.Base.BaseFeature.Initialize() in /home/thecryptohunter/projects/Redstone/src/Stratis.Bitcoin/Base/BaseFeature.cs:line 206
         at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Initialize>b__3_1(IFullNodeFeature service) in /home/thecryptohunter/projects/Redstone/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 57
         at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in /home/thecryptohunter/projects/Redstone/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 102<---
      
      ---> (Inner Exception #1) System.ArgumentNullException: Value cannot be null.
      Parameter name: block
         at Stratis.Bitcoin.Utilities.Guard.NotNull[T](T value, String parameterName) in /home/thecryptohunter/projects/Redstone/src/Stratis.Bitcoin/Utilities/Guard.cs:line 46
         at Stratis.Bitcoin.Base.Deployments.NodeDeployments.GetFlags(ChainedHeader block) in /home/thecryptohunter/projects/Redstone/src/Stratis.Bitcoin/Base/Deployments/NodeDeployments.cs:line 28
         at Stratis.Bitcoin.Features.Consensus.ConsensusFeature.Initialize() in /home/thecryptohunter/projects/Redstone/src/Stratis.Bitcoin.Features.Consensus/ConsensusFeature.cs:line 81
         at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.<>c.<Initialize>b__3_1(IFullNodeFeature service) in /home/thecryptohunter/projects/Redstone/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 57
         at Stratis.Bitcoin.Builder.FullNodeFeatureExecutor.Execute(Action`1 callback, Boolean reverseOrder) in /home/thecryptohunter/projects/Redstone/src/Stratis.Bitcoin/Builder/FullNodeFeatureExecutor.cs:line 102<---
      
There was a problem initializing the node. Details: 'One or more errors occurred. (Object reference not set to an instance of an object.) (Value cannot be null.
Parameter name: block)'
Application is shutting down...
The CancellationTokenSource has been disposed.

**Comment by thecrypt0hunter** [comment]
Requires a resync
